routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('dashboard/','DashboardController@index')->name('dashboard.index');
Route::get('auth/login','CustomAuth\AuthController@index')->name('auth.login');
Route::get('auth/register','CustomAuth\AuthController@register')->name('auth.register');
Route::post('auth','CustomAuth\AuthController@auth')->name('auth.auth');
Route::resource('dashboard/petugas', 'Master\PetugasController');
Route::resource('dashboard/pelanggan', 'Master\PelangganController');

app/Models/Petugas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Arr;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Realisasi;
use App\Models\Keluhan;

class Petugas extends Authenticatable
{
    //
    use softDeletes;
    use Notifiable;

    protected $table = 'petugas';

    protected $fillable = [
	    'role_id',
      'petugas_nip',
      'petugas_nama',
      'petugas_jabatan',
      'petugas_alamat',
		  'petugas_tanggal_lahir',
		  'petugas_jk',
      'petugas_foto',
      'petugas_username',
		  'petugas_password',
		  'is_diganti',
	];

	/**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
	protected $hidden = [
        'password', 'remember_token',
    ];

	public function getAuthPassword()
	{
		return $this->petugas_password;
	}

    static public function storeRule($withPhoto = false)
	{
		$rules = [
			'petugas_nip' => 'unique:petugas,petugas_nip',
			'petugas_nama' => 'required',
			'petugas_jabatan' => 'required',
			'petugas_alamat' => 'required',
			'petugas_tanggal_lahir' => 'required',
		];

		if ($withPhoto) {
			$rules = Arr::add(
				$rules,
				'petugas_photo',
				'required|image|mimes:jpg,jpeg,png|max:2048'
			);
		}

		return $rules;
    }

    static public function updateRule($withPhoto = false)
	{
		$rules = [
			'users_name' => 'required',
			'users_npm' => 'required',
			'users_datebirth' => 'required',
			'users_email' => 'required',
			'users_gender' => 'required',
			'users_phone' => 'required',
			'users_address' => 'required',
		];

		if ($withPhoto) {
			$rules = Arr::add(
				$rules,
				'users_photo',
				'required|image|mimes:jpg,jpeg,png|max:2048'
			);
		}

		return $rules;
	}

	public function realisasi() {
        return $this->hasMany(Realisasi::class);
	}

	public function keluhan() {
		return $this->hasMany(Keluhan::class);
	}
}

app/Http/Controllers/Master/PetugasController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use Auth;
use Hash;
use App\Helper\Log;
use App\Models\Petugas;
use App\Models\Role;
use App\Models\App;
use App\Models\Settings;
use App\Models\Keluhan;
use App\Models\Realisasi;

class PetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = "Admin Dashboard - List Pegawai";
        $petugas = Petugas::all();
        $settings = Settings::all();
		    return view('Dashboard.back.Petugas.petugas',compact(
            'title',
            'petugas',
            'settings'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $title = "Dashboard - Petugas";
        $settings = Settings::all();
        return view('Dashboard.back.Petugas.create',compact(
            'title',
            'settings'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Validator::make(
            $request->all(),
            Petugas::storeRule(),
            App::ValidationMessage()
        )->validate();

        if($request->petugas_jabatan == 1) {
            $jabatan = "Admin";
            $nip_petugas = "SA".date('Ymd').rand(1,100);
        } else if($request->petugas_jabatan == 2) {
            $jabatan = "Petugas Kantor";
            $nip_petugas = "PK".date('Ymd').rand(1,100);
        } else if($request->petugas_jabatan == 3) {
            $jabatan = "Petugas Lapangan";
            $nip_petugas = "PL".date('Ymd').rand(1,100);
        }

        if($request->petugas_foto != NULL){
            $foto = $request->file('petugas_foto');
			      $path  = 'public/assets/petugas';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = $nip_petugas.".".$ext;
            $foto->move($path,$namafoto);
            $upload = $path.'/'.$namafoto;
        } else{
            $upload   = NULL;
        }

        $insert = Petugas::create([
            'role_id' => $request->petugas_jabatan,
            'petugas_nip' => $nip_petugas,
            'petugas_nama' => $request->petugas_nama,
            'petugas_alamat' => $request->petugas_alamat,
            'petugas_tanggal_lahir' => $request->petugas_tanggal_lahir,
            'petugas_jk' => $request->petugas_jk,
            'petugas_jabatan' => $jabatan,
            'petugas_foto' => $upload,
            'petugas_username' => $nip_petugas,
            'petugas_password' => Hash::make($request->petugas_tanggal_lahir),
            'is_diganti' => 0,
        ]);

        if($insert) {
          Log::InsertLogAct(Auth::guard('petugas')->user()->id,'Petugas');
            return redirect()->route('petugas.index')->with([
              'success' => 'Penambahan Data Sukses',
          ]);
        } else {
          return redirect()->back()->withErrors(['Penambahan Data Petugas Gagal']);
        }

        // return redirect()->route('petugas.index')->with([
        //     'success' => 'Penambahan Data Sukses',
        // ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $title = "Dashboard - Petugas";
        $settings = Settings::all();
        $petugas = Petugas::where('id',$id)->get();
        return view('Dashboard.back.Petugas.edit',compact(
            'title',
            'petugas',
            'settings'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        Validator::make(
            $request->all(),
            Petugas::storeRule(),
            App::ValidationMessage()
        )->validate();

        $petugas = Petugas::find($id);

        $nip_petugas = $petugas->petugas_nip;

        if($request->petugas_foto != NULL){
            if($petugas->petugas_foto != NULL) {
                // $pecah_link = explode("/",$delete_petugas->petugas_foto);
                // $link = $pecah_link[1]."/".$pecah_link[2]."/".$pecah_link[3]."/".$pecah_link[4];
                unlink($petugas->petugas_foto);
            }
            $foto = $request->file('petugas_foto');
			      $path  = 'public/assets/petugas';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = $nip_petugas.".".$ext;
            $foto->move($path,$namafoto);
            $upload =  $path.'/'.$namafoto;
        } else{
            $upload   = $petugas->petugas_foto;
        }

        if($request->petugas_jabatan == 1) {
            $jabatan = "Admin";
        } else if($request->petugas_jabatan == 2) {
            $jabatan = "Petugas Kantor";
        } else if($request->petugas_jabatan == 3) {
            $jabatan = "Petugas Lapangan";
        }

        $update = $petugas->update([
            'role_id' => $request->petugas_jabatan,
            'petugas_nip' => $nip_petugas,
            'petugas_nama' => $request->petugas_nama,
            'petugas_alamat' => $request->petugas_alamat,
            'petugas_tanggal_lahir' => $request->petugas_tanggal_lahir,
            'petugas_jk' => $request->petugas_jk,
            'petugas_jabatan' => $jabatan,
            'petugas_foto' => $upload,
            'petugas_username' => $nip_petugas,
            'petugas_password' => $petugas->petugas_password,
            'is_diganti' => 0,
        ]);

        if($update) {
          Log::UpdateLogAct(Auth::guard('petugas')->user()->id,'Petugas');
            return redirect()->route('petugas.index')->with([
              'success' => 'Update Data Sukses',
          ]);
        } else {
          return redirect()->back()->withErrors(['Penambahan Data Petugas Gagal']);
        }

        // return redirect()->route('petugas.index')->with([
        //     'success' => 'Data Sukses Diubah',
        // ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Delete Keluhan Dulu (Foreign Key) Khusus Petugas Kantor
        $hitung_keluhan = Keluhan::all()->count();
        if($hitung_keluhan > 0) {
            $keluhan_all = Keluhan::all();
            foreach($keluhan_all as $kel) {
                $id_pet = $kel['petugas_id'];
            }
            if($id == $id_pet) {
                $hitung_keluhan_by_id = Keluhan::where('petugas_id',$id)->count();
                if($hitung_keluhan_by_id > 0) {
                    $delete_keluhan = Keluhan::where('petugas_id',$id)->first();
                    $delete_keluhan->delete();
                }
            }
        }

        // Delete Realisasi (Foreign Key) Khusus Petugas Lapangan
        $hitung_realisasi = Realisasi::all()->count();
        if($hitung_realisasi > 0) {
            $realisasi_all = Realisasi::all();
            foreach($realisasi_all as $rel) {
                $id_pet = $rel['petugas_id'];
            }
            if($id == $id_pet) {
                $hitung_realisasi_by_id = Realisasi::where('petugas_id',$id)->count();
                if($hitung_realisasi_by_id > 0) {
                    $delete_realisasi = Realisasi::where('petugas_id',$id)->first();
                    if($delete_realisasi->foto_realiasasi_1 != NULL) {
                        unlink($delete_realisasi->foto_realiasasi_1);
                    } else if($delete_realisasi->foto_realiasasi_2 != NULL) {
                        unlink($delete_realisasi->foto_realiasasi_2);
                    } else if($delete_realisasi->foto_realiasasi_3 != NULL) {
                        unlink($delete_realisasi->foto_realiasasi_3);
                    } else if($delete_realisasi->foto_realiasasi_4 != NULL) {
                        unlink($delete_realisasi->foto_realiasasi_4);
                    }
                    $delete_realisasi->delete();
                }
            }
        }

        // Jika tidak ada nilai value pada Foreign Key otomatis akan menghapus Data Petugas
        $delete_petugas = Petugas::where('id',$id)->first();
        if($delete_petugas->petugas_foto != NULL){
            unlink($delete_petugas->petugas_foto);
        }
        $delete_petugas->delete();
        Log::DeleteLogAct(Auth::guard('petugas')->user()->id,'Petugas');
        return redirect()->route('petugas.index')->with([
            'success' => 'Data Berhasil Dihapus',
        ]);
    }

    public function changePass($id) {
        $title = "Dashboard - Petugas";
        $settings = Settings::all();
        $petugas = Petugas::where('id',$id)->get();
        return view('Dashboard.back.Petugas.password',compact(
            'title',
            'petugas',
            'settings'
        ));
    }

    public function password(Request $request, $id) {
        $petugas = Petugas::find($id);
        if($petugas->petugas_tanggal_lahir == $request->old_password) {
            if($request->new_password == $request->new_password_repeat) {
                $petugas->update([
                    'petugas_password' => Hash::make($request->new_password),
                    'is_diganti' => 1,
                ]);
            } else {

resources/views/Dashboard/back/Petugas/create.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Petugas</h1>
@if($msg = Session::get('success'))                                               
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif

<!--- Form -->
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif	

<form method="post" action="{{route('petugas.store')}}" enctype="multipart/form-data">
	{{csrf_field()}}
        <center>
            <br/>
            <br/>
        <div class="col-sm-5">
          <div class="form-group">
            <input type="text" class="form-control form-control-user" id="exampleFirstName" name="petugas_nama" placeholder="Nama Petugas">
          </div>
          <div class="form-group">
              <select name="petugas_jabatan" class="form-control form-control-user">
                  <option value="">Pilih Jabatan</option>
                  <option value="1">Admin</option>
                  <option value="2">Petugas Kantor</option>
                  <option value="3">Petugas Lapangan</option>
              </select>
            </div>  
        <div class="form-group">
          <textarea class="form-control form-control-user" id="exampleInputAlamat" name="petugas_alamat" placeholder="Alamat"></textarea>
        </div>
          <div class="form-group">
            <input type="date" class="form-control form-control-user" id="exampleInputtgl" name="petugas_tanggal_lahir" placeholder="Tanggal Lahir">
          </div>
          <div class = "form-group">
            <select name="petugas_jk" class="form-control form-control-user">
              <option value="">Pilih Jenis Kelamin</option>
                <option value="L">Laki-laki</option>
                <option value="P">Perempuan</option>
              </select>
          </div>    
          <div class="form-group">
            <div class="form-grop text-left">
              <input type="file" name="petugas_foto" placeholder="Tulis Sipnosis" onchange="preview(this,'gambar')">
            </div>
        </div>
        <div class="form-group">
            <img src="" width = "250" class="rendered img-fluid mt-2" id="gambar" alt=""/>
        </div>
        <button class="btn btn-primary btn-user btn-block">
          <i class = "fa fa-save"></i> Simpan
        </button>
        <hr>
</center>
</form>
  
<script charset="utf-8">

  function preview(gambar,idpreview){
        var gb = gambar.files;
              for (var i = 0; i < gb.length; i++){
                  var gbPreview = gb[i];
                  var imageType = /image.*/;
                  var preview=document.getElementById(idpreview);
                  var reader = new FileReader();
                      if (gbPreview.type.match(imageType)) {
                          preview.file = gbPreview;
                          reader.onload = (function(element) {
                              return function(e) {
                                  element.src = e.target.result;
                              };
                          })(preview);
                          reader.readAsDataURL(gbPreview);
                      } else{
                          alert("Type file tidak sesuai. Khusus image.");
                      }
                  }
              }
        
        </script>

@endsection

resources/views/Dashboard/back/Petugas/edit.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Petugas</h1>
@if($msg = Session::get('success'))
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif

<!--- Form -->
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif

@foreach($petugas as $hasil)
<form method="post" action="{{route('petugas.update',$hasil['id'])}}" enctype="multipart/form-data">
    {{csrf_field()}}
    {{method_field('PUT')}}
        <center>
            <br/>
            <br/>
        <div class="col-sm-5">
          <div class="form-group">
          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="petugas_nama" placeholder="Nama Petugas" value="{{ $hasil['petugas_nama'] }}">
          </div>
          <div class="form-group">
              <select name="petugas_jabatan" class="form-control form-control-user">
                  <option value="">Pilih Jabatan</option>
                  @if($hasil['petugas_jabatan'] == "Admin")
                    <option value="1" selected>Admin</option>
                    <option value="2">Petugas Kantor</option>
                    <option value="3">Petugas Lapangan</option>
                  @elseif($hasil['petugas_jabatan'] == "Petugas Kantor")
                    <option value="1">Admin</option>
                    <option value="2" selected>Petugas Kantor</option>
                    <option value="3">Petugas Lapangan</option>
                  @elseif($hasil['petugas_jabatan'] == "Petugas Lapangan")
                    <option value="1">Admin</option>
                    <option value="2">Petugas Kantor</option>
                    <option value="3" selected>Petugas Lapangan</option>
                  @endif
              </select>
            </div>
        <div class="form-group">
        <textarea class="form-control form-control-user" id="exampleInputAlamat" name="petugas_alamat" placeholder="Alamat">{{ $hasil['petugas_alamat'] }}</textarea>
        </div>
          <div class="form-group">
          <input type="date" class="form-control form-control-user" id="exampleInputtgl" name="petugas_tanggal_lahir" placeholder="Tanggal Lahir" value="{{ $hasil['petugas_tanggal_lahir'] }}">
          </div>
          <div class = "form-group">
            <select name="petugas_jk" class="form-control form-control-user">
              <option value="">Pilih Jenis Kelamin</option>
                @if($hasil['petugas_jk'] == "L")
                    <option value="L" selected>Laki-laki</option>
                    <option value="P">Perempuan</option>
                @elseif($hasil['petugas_jk'] == "P")
                    <option value="L">Laki-laki</option>
                    <option value="P" selected>Perempuan</option>
                @elseif($hasil['petugas_jk'] == NULL)
                    <option value= "L">Laki-laki</option>
                    <option value= "P">Perempuan</option>
                @endif
              </select>
          </div>
          <div class="form-group">
            <div class="form-grop text-left">
              <input type="file" name="petugas_foto" placeholder="Tulis Sipnosis" onchange="preview(this,'gambar')">
            </div>
        </div>
        <div class="form-group">
          <img src="{{ asset($hasil['petugas_foto']) }}" width = "250" class="rendered img-fluid mt-2" id="gambar" alt=""/>
        </div>
        <button class="btn btn-primary btn-user btn-block">
          <i class = "fa fa-save"></i> Simpan
        </button>
        <hr>
</center>
</form>
@endforeach

<script charset="utf-8">

  function preview(gambar,idpreview){
        var gb = gambar.files;
              for (var i = 0; i < gb.length; i++){
                  var gbPreview = gb[i];
                  var imageType = /image.*/;
                  var preview=document.getElementById(idpreview);
                  var reader = new FileReader();
                      if (gbPreview.type.match(imageType)) {
                          preview.file = gbPreview;
                          reader.onload = (function(element) {
                              return function(e) {
                                  element.src = e.target.result;
                              };
                          })(preview);
                          reader.readAsDataURL(gbPreview);
                      } else{
                          alert("Type file tidak sesuai. Khusus image.");
                      }
                  }
              }

        </script>

@endsection

resources/views/Dashboard/back/Petugas/password.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Petugas</h1>
@if($msg = Session::get('success'))                                               
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif

<!--- Form -->
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			    <li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif	

@foreach($petugas as $hasil)
<form method="post" action="{{route('petugas.password',$hasil['id'])}}" enctype="multipart/form-data">
    {{csrf_field()}}
    {{method_field('PUT')}}
        <center>
            <br/>
            <br/>
        <div class="col-sm-5">
            <div class="form-group">
                <div class="form-grop text-left">
                    <input type="password" class="form-control form-control-user" name="old_password" placeholder="Tulis Password Lama Anda">
                </div>
            </div>
            <div class="form-group">
                <div class="form-grop text-left">
                    <input type="password" class="form-control form-control-user" name="new_password" placeholder="Tulis Password Baru Anda">
                </div>
            </div>
            <div class="form-group">
                <div class="form-grop text-left">
                    <input type="password" class="form-control form-control-user" name="new_password_repeat" placeholder="Tulis Password Baru Anda Sekali Lagi">
                </div>
            </div>
        <button class="btn btn-primary btn-user btn-block">
          <i class = "fa fa-save"></i> Simpan
        </button>
        <hr>
    </div>  
</center>
</form>
@endforeach
  

@endsection

resources/views/Dashboard/back/Petugas/petugas.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Petugas</h1>
@if($msg = Session::get('success'))
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif
<a href="{{route('petugas.create')}}" button type="button" class="btn btn-primary pull-right">
  <span class="fa fa-plus"></span> Tambah Data</a>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="Petugas-tables" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Foto</th>
            <th>NIP</th>
            <th>Nama Petugas</th>
            <th>Jabatan Petugas</th>
            <th>Alamat Petugas</th>
            <th>Tanggal Lahir Petugas</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Foto</th>
            <th>NIP</th>
            <th>Nama Petugas</th>
            <th>Jabatan Petugas</th>
            <th>Alamat Petugas</th>
            <th>Tanggal Lahir Petugas</th>
            <th>Aksi</th>
          </tr>
        </tfoot>
        <tbody>
            @foreach($petugas as $hasil)
            <tr>
                <td><img width="100" src = "{{ asset($hasil['petugas_foto']) }}"></td>
                <td>{{ $hasil['petugas_nip'] }}</td>
                <td>{{ $hasil['petugas_nama']}}</td>
                <td>{{ $hasil['petugas_jabatan'] }}</td>
                <td>{{ $hasil['petugas_alamat'] }}</td>
                <td>{{ $hasil['petugas_tanggal_lahir'] }}</td>
                <form action="{{route('petugas.destroy' ,$hasil['id'])}}" method="post">
                  {{csrf_field()}}
                  {{method_field('DELETE')}}
                  <td><center><button type="submit" class="btn btn-danger btn-sm" name="_method" value="Delete" onclick="return confirm('Yakin Hapus Data ??')"><i class="fa fa-trash"></i></button></form>
                  <a href="{{route('petugas.edit',$hasil['id'])}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a></td>
            </tr>
            @endforeach
        </tbody>
    </table>
  </div>
</div>
</div>
</div>

@endsection