routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('dashboard/','DashboardController@index')->name('dashboard.index');
Route::get('auth/login','CustomAuth\AuthController@index')->name('auth.login');
Route::get('auth/register','CustomAuth\AuthController@register')->name('auth.register');
Route::post('auth','CustomAuth\AuthController@auth')->name('auth.auth');
Route::resource('dashboard/petugas', 'Master\PetugasController');
Route::resource('dashboard/pelanggan', 'Master\PelangganController');

app/Models/Pelanggan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Arr;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Keluhan;

class Pelanggan extends Authenticatable
{
    //
    use softDeletes;
    use Notifiable;

    protected $table = 'pelanggan';

    protected $fillable = [
	    'role_id',
      'pelanggan_id',
      'pelanggan_nama',
		  'pelanggan_alamat',
      'pelanggan_telepon',
		  'pelanggan_jk',
      'pelanggan_tanggal_lahir',
      'pelanggan_foto',
      'pelanggan_username',
      'pelanggan_password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
	protected $hidden = [
        'password', 'remember_token',
    ];

	public function getAuthPassword()
	{
		return $this->pelanggan_password;
	}

    static public function storeRule($withPhoto = false)
	{
		$rules = [
			'pelanggan_id' => 'unique:pelanggan,pelanggan_id',
			'pelanggan_nama' => 'required',
			'pelanggan_alamat' => 'required',
			'pelanggan_tanggal_lahir' => 'required',
		];

		if ($withPhoto) {
			$rules = Arr::add(
				$rules,
				'pelanggan_photo',
				'required|image|mimes:jpg,jpeg,png|max:2048'
			);
		}

		return $rules;
    }

    static public function updateRule($withPhoto = false)
	{
		$rules = [
			'users_name' => 'required',
			'users_npm' => 'required',
			'users_datebirth' => 'required',
			'users_email' => 'required',
			'users_gender' => 'required',
			'users_phone' => 'required',
			'users_address' => 'required',
		];

		if ($withPhoto) {
			$rules = Arr::add(
				$rules,
				'pelanggan_foto',
				'required|image|mimes:jpg,jpeg,png|max:2048'
			);
		}

		return $rules;
	}


    public function keluhan() {
        return $this->hasMany(Keluhan::class);
    }
}

app/Http/Controllers/Master/PelangganController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use Auth;
use Hash;
use DB;
use App\Helper\Log;
use App\Models\Pelanggan;
use App\Models\Keluhan;
use App\Models\Role;
use App\Models\Settings;
use App\Models\App;

class PelangganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = "Dashboard - Pelanggan";
        $settings = Settings::all();
        $pelanggan = Pelanggan::all();
        return view('Dashboard.back.Pelanggan.pelanggan',compact(
            'title',
            'pelanggan',
            'settings'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $title = "Dashboard - Pelanggan";
        $settings = Settings::all();
        return view('Dashboard.back.Pelanggan.create',compact(
            'title',
            'settings',
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Validator::make(
            $request->all(),
            Pelanggan::storeRule(),
            App::ValidationMessage()
        )->validate();

        $id_pelanggan = date('Ymd').rand(1,100);

        if($request->pelanggan_foto != NULL){
            $foto = $request->file('pelanggan_foto');
			      $path  = 'public/assets/pelanggan';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = $id_pelanggan.".".$ext;
            $foto->move($path,$namafoto);
            $upload =  $path.'/'.$namafoto;
        } else{
            $upload   = '/assets/images/default/default.png';
        }

        $insert = Pelanggan::create([
            'role_id' => 3,
            'pelanggan_id' => $id_pelanggan,
            'pelanggan_nama' => $request->pelanggan_nama,
            'pelanggan_alamat' => $request->pelanggan_alamat,
            'pelanggan_tanggal_lahir' => $request->pelanggan_tanggal_lahir,
            'pelanggan_jk' => $request->pelanggan_jk,
            'pelanggan_telepon' => $request->pelanggan_telepon,
            'pelanggan_foto' => $upload,
            'pelanggan_username' => $id_pelanggan,
            'pelanggan_password' => Hash::make($request->pelanggan_tanggal_lahir),
        ]);

        if($insert) {
          Log::InsertLogAct(Auth::guard('petugas')->user()->id,'Pelanggan');
          return redirect()->route('pelanggan.index')->with([
              'success' => 'Penambahan Data Sukses',
          ]);
        }



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $title = 'Dashboard - Pelanggan';
        $settings = Settings::all();
        $pelanggan = Pelanggan::where('id',$id)->get();
        return view('Dashboard.back.Pelanggan.edit',compact(
            'title',
            'pelanggan',
            'settings'
        ));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        Validator::make(
            $request->all(),
            Pelanggan::storeRule(),
            App::ValidationMessage()
        )->validate();

        //$id_pelanggan = date('Ymd').rand(1,100);

        $pelanggan = Pelanggan::find($id);

        $id_pelanggan = $pelanggan->pelanggan_id;

        if($request->pelanggan_foto != NULL){
            if($pelanggan->pelanggan_foto != NULL) {
                unlink($pelanggan->pelanggan_foto);
            }
            $foto = $request->file('pelanggan_foto');
			      $path  = 'public/assets/pelanggan';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = $id_pelanggan.".".$ext;
            $foto->move($path,$namafoto);
            $upload =  $path.'/'.$namafoto;
        } else{
            $upload   = $pelanggan->pelanggan_foto;
        }

        $pelanggan = Pelanggan::find($id);

        $update = $pelanggan->update([
            'role_id' => 3,
            'pelanggan_id' => $id_pelanggan,
            'pelanggan_nama' => $request->pelanggan_nama,
            'pelanggan_alamat' => $request->pelanggan_alamat,
            'pelanggan_tanggal_lahir' => $request->pelanggan_tanggal_lahir,
            'pelanggan_jk' => $request->pelanggan_jk,
            'pelanggan_telepon' => $request->pelanggan_telepon,
            'pelanggan_foto' => $upload,
            'pelanggan_username' => $id_pelanggan,
            'pelanggan_password' => Hash::make($request->pelanggan_tanggal_lahir),
        ]);

        if($update) {
          Log::UpdateLogAct(Auth::guard('petugas')->user()->id,'Pelanggan');
          return redirect()->route('pelanggan.index')->with([
              'success' =>  'Data Sukses Diubah',
          ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete_keluhan = Keluhan::where('pelanggan_id',$id)->delete();
        $delete_pelanggan = Pelanggan::where('id',$id)->first();
        if($delete_pelanggan->foto_pelanggan != NULL){
            unlink($delete_pelanggan->foto_pelanggan);
        }
        $delete_pelanggan->delete();
        Log::DeleteLogAct(Auth::guard('petugas')->user()->id,'Pelanggan');
        return redirect()->route('pelanggan.index')->with([
            'success' => 'Data Berhasil Dihapus',
        ]);
    }
}

resources/views/Dashboard/back/Pelanggan/create.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Pelanggan</h1>
@if($msg = Session::get('success'))
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif

<!--- Form -->
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif
<form method="post" action="{{route('pelanggan.store')}}" enctype="multipart/form-data">
	{{csrf_field()}}
        <center>
            <br/>
            <br/>
        <div class="col-sm-5">
          <div class="form-group">
            <input type="text" class="form-control form-control-user" id="exampleFirstName" name="pelanggan_nama" placeholder="Nama Anda">
          </div>
        <div class="form-group">
          <textarea class="form-control form-control-user" id="exampleInputAlamat" name="pelanggan_alamat" placeholder="Alamat"></textarea>
        </div>
          <div class="form-group">
            <input type="date" class="form-control form-control-user" id="exampleInputtgl" name="pelanggan_tanggal_lahir" placeholder="Tanggal Lahir">
          </div>
          <div class="form-group">
            <input type="number" class="form-control form-control-user" id="exampleInputtlpn" name="pelanggan_telepon" placeholder="Nomor Telepon">
          </div>
          <div class = "form-group">
            <select name="pelanggan_jk" class="form-control form-control-user">
              <option value="">Pilih</option>
                <option value="L">Laki-laki</option>
                <option value="P">Perempuan</option>
              </select>
          </div>
          <div class="form-group">
            <div class="form-grop text-left">
              <input type="file" name="pelanggan_foto" placeholder="Tulis Sipnosis" onchange="preview(this,'gambar')">
            </div>
        </div>
        <div class="form-group">
            <img src="" width = "250" class="rendered img-fluid mt-2" id="gambar" alt=""/>
        </div>
        <button class="btn btn-primary btn-user btn-block">
          Daftar Baru
        </button>
        <hr>
</center>
</form>

<script charset="utf-8">

  function preview(gambar,idpreview){
        var gb = gambar.files;
              for (var i = 0; i < gb.length; i++){
                  var gbPreview = gb[i];
                  var imageType = /image.*/;
                  var preview=document.getElementById(idpreview);
                  var reader = new FileReader();
                      if (gbPreview.type.match(imageType)) {
                          preview.file = gbPreview;
                          reader.onload = (function(element) {
                              return function(e) {
                                  element.src = e.target.result;
                              };
                          })(preview);
                          reader.readAsDataURL(gbPreview);
                      } else{
                          alert("Type file tidak sesuai. Khusus image.");
                      }
                  }
              }

        </script>

@endsection

resources/views/Dashboard/back/Pelanggan/edit.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Pelanggan</h1>
@if($msg = Session::get('success'))
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif

<!--- Form -->
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif

@foreach($pelanggan as $pelanggans)
<form method="post" action="{{route('pelanggan.update',$pelanggans['id'])}}" enctype="multipart/form-data">
    {{csrf_field()}}
    {{method_field('PUT')}}
        <center>
            <br/>
            <br/>
        <div class="col-sm-5">
          <div class="form-group">
          <input type="text" class="form-control form-control-user" id="exampleFirstName" name="pelanggan_nama" placeholder="Nama Anda" value="{{ $pelanggans['pelanggan_nama'] }}">
          </div>
        <div class="form-group">
        <textarea class="form-control form-control-user" id="exampleInputAlamat" name="pelanggan_alamat" placeholder="Alamat">{{ $pelanggans['pelanggan_alamat'] }}</textarea>
        </div>
          <div class="form-group">
          <input type="date" class="form-control form-control-user" id="exampleInputtgl" name="pelanggan_tanggal_lahir" placeholder="Tanggal Lahir" value="{{ $pelanggans['pelanggan_tanggal_lahir'] }}">
          </div>
          <div class="form-group">
            <input type="number" class="form-control form-control-user" id="exampleInputtlpn" name="pelanggan_telepon" placeholder="Nomor Telepon" value="{{ $pelanggans['pelanggan_telepon'] }}">
          </div>
          <div class = "form-group">
            <select name="pelanggan_jk" class="form-control form-control-user">
              <option value="">Pilih</option>
                @if($pelanggans['pelanggan_jk'] == "L")
                    <option value= "L" selected>Laki-laki</option>
                    <option value= "P">Perempuan</option>
                @elseif($pelanggans['pelanggan_jk'] == "P")
                    <option value= "P" selected>Perempuan</option>
                    <option value= "L">Laki-laki</option>
                @elseif($pelanggans['pelanggan_jk'] == NULL)
                    <option value= "L">Laki-laki</option>
                    <option value= "P">Perempuan</option>
                @endif
              </select>
          </div>
          <div class="form-group">
            <div class="form-grop text-left">
              <input type="file" name="pelanggan_foto" placeholder="Tulis Sipnosis" onchange="preview(this,'gambar')">
            </div>
        </div>
        <div class="form-group">
        <img src="{{ asset($pelanggans['pelanggan_foto']) }}" width = "250" class="rendered img-fluid mt-2" id="gambar" alt=""/>
        </div>
        <button class="btn btn-primary btn-user btn-block">
          Simpan
        </button>
        <hr>
</center>
</form>
@endforeach

<script charset="utf-8">

  function preview(gambar,idpreview){
        var gb = gambar.files;
              for (var i = 0; i < gb.length; i++){
                  var gbPreview = gb[i];
                  var imageType = /image.*/;
                  var preview=document.getElementById(idpreview);
                  var reader = new FileReader();
                      if (gbPreview.type.match(imageType)) {
                          preview.file = gbPreview;
                          reader.onload = (function(element) {
                              return function(e) {
                                  element.src = e.target.result;
                              };
                          })(preview);
                          reader.readAsDataURL(gbPreview);
                      } else{
                          alert("Type file tidak sesuai. Khusus image.");
                      }
                  }
              }

        </script>

@endsection

resources/views/Dashboard/back/Pelanggan/pelanggan.blade.php
@extends('Dashboard.app')

@section('content')

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Pelanggan</h1>
@if($msg = Session::get('success'))
  <div class="alert alert-success">
    {{ $msg }}
  </div>
@endif
<a href="{{route('pelanggan.create')}}" button type="button" class="btn btn-primary pull-right">
  <span class="fa fa-plus"></span> Tambah Data</a>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="Pelanggan-tables" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>No</th>
            <th>Foto</th>
            <th>ID Pelanggan</th>
            <th>Nama Pelanggan</th>
            <th>No Telepon Pelanggan</th>
            <th>Alamat Pelanggan</th>
            <th>Tanggal Lahir Pelanggan</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>No</th>
            <th>Foto</th>
            <th>ID Pelanggan</th>
            <th>Nama Pelanggan</th>
            <th>No Telepon Pelanggan</th>
            <th>Alamat Pelanggan</th>
            <th>Tanggal Lahir Pelanggan</th>
            <th>Aksi</th>
          </tr>
        </tfoot>
        <tbody>
          @php $no = 1; @endphp
            @foreach($pelanggan as $hasil)
            <tr>
              <td>{{ $no++ }}</td>
                <td><img width = "100" src = "{{ asset($hasil['pelanggan_foto']) }}"></td>
                <td>{{ $hasil['pelanggan_id'] }}</td>
                <td>{{ $hasil['pelanggan_nama']}}</td>
                <td>{{ $hasil['pelanggan_telepon']}}</td>
                <td>{{ $hasil['pelanggan_alamat'] }}</td>
                <td>{{ $hasil['pelanggan_tanggal_lahir'] }}</td>
                <form action="{{route('pelanggan.destroy' ,$hasil['id'])}}" method="post">
                  {{csrf_field()}}
                  {{method_field('DELETE')}}
                  <td><center><button type="submit" class="btn btn-danger btn-sm" name="_method" value="Delete" onclick="return confirm('Yakin Hapus Data ??')"><i class="fa fa-trash"></i></button></form>
                  <a href="{{route('pelanggan.edit',$hasil['id'])}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a></td>
            </tr>
            @endforeach
        </tbody>
    </table>
  </div>
</div>
</div>
</div>

@endsection