routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('dashboard/','DashboardController@index')->name('dashboard.index');
Route::get('auth/login','CustomAuth\AuthController@index')->name('auth.login');
Route::get('auth/register','CustomAuth\AuthController@register')->name('auth.register');
Route::post('auth','CustomAuth\AuthController@auth')->name('auth.auth');
Route::resource('dashboard/petugas', 'Master\PetugasController');
Route::resource('dashboard/pelanggan', 'Master\PelangganController');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Jenssegers\Agent\Agent;
use App\Models\Pelanggan;
use App\Models\Petugas;
use App\Models\Ticket;
use App\Models\Keluhan;
use App\Models\Settings;
use App\Models\LoginAgents;

class DashboardController extends Controller
{
    //
    public function index() {
        $title = 'Dashboard';
        $agent = new Agent();
        $settings = Settings::all();
        $pelanggan = Pelanggan::all()->count();
        $petugas = Petugas::all()->count();
        $keluhan = Keluhan::all()->count();
        $ticket = Ticket::where('is_diambil',0)->count();
        return view('Dashboard.pages.dashboard',compact(
            'title',
            'pelanggan',
            'petugas',
            'keluhan',
            'ticket',
            'settings'
        ));
    }

    public function getSettingsLayout() {

        $settings = Settings::where('id',1)->get();
        $title = 'Dashboard - Pengaturan';
        return view('Dashboard.pages.settings',compact(
            'settings',
            'title',
        ));
    }

    public function setSettings(Request $request, $id) {

        $dashboard = Settings::find($id);

        if($request->login_image != NULL){
            if($dashboard->login_image != NULL) {
                //chmod($dashboard->login_image, 0777);
                unlink($dashboard->login_image);
            }
            $foto = $request->file('login_image');
			      $path  = 'public/assets/settings';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = "login".".".$ext;
            $foto->move($path,$namafoto);
            $upload1 =  $path.'/'.$namafoto;
        } else{
            $upload1   = $dashboard->login_image;
        }

        if($request->register_image != NULL){
            if($dashboard->register_image != NULL) {
                chmod($dashboard->register_image, 0777);
                unlink($dashboard->register_image);
            }
            $foto = $request->file('register_image');
			      $path  = 'public/assets/settings';
        	  $ext = $foto->getClientOriginalExtension();
            $namafoto = "register".".".$ext;
            $foto->move($path,$namafoto);
            $upload2 =  $path.'/'.$namafoto;
        } else{
            $upload2   = $dashboard->register_image;
        }

        $dashboard->update([
            'dashboard_name' => $request->dashboard_name,
            'login_image' => $upload1,
            'register_image' => $upload2,
        ]);

        return redirect()->route('dashboard.index')->with([
            'success' => 'Dashboard Sukses Diubah',
        ]);
    }

    public function setLoginActivity() {
      $loginactivity = LoginAgents::all();
      $settings = Settings::where('id',1)->get();
      $title = 'Dashboard - Aktivitas Login';
      return view ('Dashboard.pages.loginactivity',compact(
        'title',
        'settings',
        'loginactivity',
      ));
    }
}

resources/views/Dashboard/modules/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
      <span>Copyright &copy; Your Website {{ date('Y') }}</span>
      </div>
    </div>
  </footer>

resources/views/Dashboard/modules/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>{{ $title }}</title>

<!-- CSRF Token Penting Untuk Manajemen DB -->
<meta name="csrf-token" content="{{ csrf_token() }}">
<!-- Custom fonts for this template-->
<link href="{{asset('sb-admin-2/vendor/fontawesome-free/css/all.min.css')}}"  rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{asset('sb-admin-2/css/sb-admin-2.css')}}" rel="stylesheet">

<!-- Custom styles for this page -->
<link href="{{asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">

<!-- Select2 -->
<link href="{{asset('select2/css/select2.min.css')}}" rel="stylesheet" />

resources/views/Dashboard/modules/nav.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">


      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          @if(Auth::guard('petugas')->check())
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::guard('petugas')->user()->petugas_nama }}</span>
          <img class="img-profile rounded-circle" src="{{ asset(Auth::guard('petugas')->user()->petugas_foto) }}">
          @elseif(Auth::guard('pelanggan')->check())
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::guard('pelanggan')->user()->pelanggan_nama }}</span>
          <img class="img-profile rounded-circle" src="{{ asset(Auth::guard('pelanggan')->user()->pelanggan_foto) }}">
          @endif
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            @if(Auth::guard('petugas')->check())
              {{ Auth::guard('petugas')->user()->petugas_nama }}
            @elseif(Auth::guard('pelanggan')->check())
              {{ Auth::guard('pelanggan')->user()->pelanggan_nama }}
            @endif
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Keluar
          </a>
        </div>
      </li>

    </ul>

</nav>

resources/views/Dashboard/modules/script.blade.php
<script src="{{asset('sb-admin-2/vendor/jquery/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js')}}" type="text/javascript"></script>

<!-- Core plugin JavaScript-->
<script src="{{asset('sb-admin-2/vendor/jquery-easing/jquery.easing.min.js')}}" type="text/javascript"></script>

<!-- Custom scripts for all pages-->
<script src="{{asset('sb-admin-2/js/sb-admin-2.min.js')}}" type="text/javascript"></script>

<!-- Page level plugins -->
<script src="{{asset('sb-admin-2/vendor/chart.js/Chart.min.js')}}" type="text/javascript"></script>

<!-- Page level custom scripts -->
<script src="{{asset('sb-admin-2/js/demo/chart-area-demo.js')}}" type="text/javascript"></script>
<script src="{{asset('sb-admin-2/js/demo/chart-pie-demo.js')}}" type="text/javascript"></script>

<!-- Page level plugins -->
<script src="{{asset('sb-admin-2/vendor/datatables/jquery.dataTables.min.js')}}" type="text/javascript"></script>
<script src="{{asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js')}}" type="text/javascript"></script>

<script src="{{asset('js/Dashboard/DataTables.js')}}" type="text/javascript"></script>
<script src="{{asset('js/Dashboard/Keluhan.js')}}" type="text/javascript"></script>

<script src = "{{asset('ckeditor/ckeditor.js')}}" type="text/javascript"></script>

<script src = "{{asset('select2/js/select2.min.js')}}" type="text/javascript"></script>

<script>
    CKEDITOR.replace( 'ckeditor' );
    CKEDITOR.replace( 'keluhan' );
</script>

resources/views/Dashboard/modules/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('dashboard.index')}}">
  @foreach($settings as $hasil)
    @if($hasil['dashboard_name'] == NULL)
      @php $judul = "Dashboard Name" @endphp
    @else
      @php $judul = $hasil['dashboard_name'] @endphp
    @endif
    <div class="sidebar-brand-text mx-3">{{ $judul }}</div>
  @endforeach
</a>

  <!-- Divider -->
<hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
<li class="nav-item active">
  <a class="nav-link" href="{{route('dashboard.index')}}">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span></a>
</li>

  <!-- Divider -->
<hr class="sidebar-divider">

  <!-- Heading -->
<div class="sidebar-heading">
  Master Data
</div>

  <!-- Nav Item - Pages Collapse Menu -->
@if(Auth::guard('petugas')->check())
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
    <i class="fas fa-fw fa-cog"></i>
    <span>Master Data</span>
  </a>
  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <h6 class="collapse-header">Master Data:</h6>
      @if(Auth::guard('petugas')->user()->role_id == 1)
        <a class="collapse-item" href="{{route('petugas.index')}}">Petugas</a>
        <a class="collapse-item" href="{{route('pelanggan.index')}}">Pelanggan</a>
        <a class="collapse-item" href="{{route('keluhan.index')}}">Keluhan</a>
        <a class="collapse-item" href="{{route('ticket.index')}}">Tiket</a>
        <a class="collapse-item" href="{{route('realisasi.index')}}">Realisasi</a>
      @elseif(Auth::guard('petugas')->user()->role_id == 2)
        <a class="collapse-item" href="{{route('pelanggan.index')}}">Pelanggan</a>
        <a class="collapse-item" href="{{route('keluhan.index')}}">Keluhan</a>
        <a class="collapse-item" href="{{route('ticket.index')}}">Tiket</a>
        <a class="collapse-item" href="{{route('realisasi.index')}}">Realisasi</a>
      @elseif(Auth::guard('petugas')->user()->role_id == 3)
        <a class="collapse-item" href="{{route('ticketact.index')}}">Ambil Tiket</a>
        <a class="collapse-item" href="{{route('realisasi.index')}}">Realisasi Anda</a>
      @endif
    </div>
  </div>
</li>
@endif

  <!-- Nav Item - Utilities Collapse Menu -->
@if(Auth::guard('pelanggan')->check())
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
    <i class="fas fa-fw fa-edit"></i>
    <span>Keluhan</span>
  </a>
  <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <h6 class="collapse-header">Keluhan</h6>
    <a class="collapse-item" href="{{route('keluhan.index')}}">Keluhan Anda</a>
    </div>
  </div>
</li>
@endif

  <!-- Nav Item - Utilities Collapse Menu -->
  @if(Auth::guard('petugas')->check())
    @if(Auth::guard('petugas')->user()->role_id == 1)
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-edit"></i>
      <span>Pengaturan Dashboard</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Pengaturan Dashboard</h6>
      <a class="collapse-item" href="{{route('dashboard.settings')}}">Pengaturan Dashboard</a>
      </div>
    </div>
  </li>
    @endif
  @endif

  <!-- Nav Item - Utilities Collapse Menu -->
  @if(Auth::guard('petugas')->check())
    @if(Auth::guard('petugas')->user()->role_id == 1)
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities1" aria-expanded="true" aria-controls="collapseUtilities1">
      <i class="fas fa-fw fa-history"></i>
      <span>Aktivitas</span>
    </a>
    <div id="collapseUtilities1" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Aktivitas Login</h6>
      <a class="collapse-item" href="{{route('dashboard.loginactivity')}}">Aktivitas Login</a>
      </div>
    </div>
  </li>
    @endif
  @endif

</ul>